config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "store/index"
  root :to => "store#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    resources :stocks, only: [:new, :create], module: :products
  end
  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
  end
  resources :carts
  resources :orders do
      match "/guest" => "orders#guest",  via: [:post], on: :member
      match "/print" => "orders#print",  via: [:get], on: :member
      match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
      match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
      match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection



    end
  resources :members do
    resources :payments, only: [:new, :create], module: :members
    resources :line_items, only: [:index], module: :members do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :members
    end
  end
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do 
    resources :payments, only: [:new, :create], module: :suppliers
  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :categories
  resources :wholesales
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks

  end
  namespace :wholesales do
    resources :line_items
    resources :orders
  end
  resources :businesses
  resources :info, only: [:index]
  resources :users, only: [:show, :edit, :update]
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index]
  namespace :accounting do
    resources :balance_sheet, only:[:index]
    resources :income_statement, only:[:index]
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member

    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :entries do
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :warranties, only: [:new, :create]
  resources :birs
  resources :retail_pricelists, only: [:index]
  resources :wholesale_pricelists, only: [:index]

end

app/models/accounting/account.rb
module Accounting
  class Account < ApplicationRecord
    include PgSearch
    pg_search_scope :search_by_name, :against => [:name, :type]
    class_attribute :normal_credit_balance
    enum status: [:active, :inactive]
    belongs_to :main_account, class_name: "Accounting::Account"
    has_many :amounts, -> { includes(:credit_amounts, :debit_amounts)}
    has_many :sub_accounts, class_name: "Accounting::Account", foreign_key: 'main_account_id'
    has_many :credit_amounts, :extend => Accounting::AmountsExtension, :class_name => 'Accounting::CreditAmount'
    has_many :debit_amounts, :extend => Accounting::AmountsExtension, :class_name => 'Accounting::DebitAmount'
    has_many :entries, through: :amounts, source: :entry, class_name: "Accounting::Entry"
    has_many :credit_entries, :through => :credit_amounts, :source => :entry, :class_name => 'Accounting::Entry'
    has_many :debit_entries, :through => :debit_amounts, :source => :entry, :class_name => 'Accounting::Entry'

    validates :type, :name, :code, presence: true
    validates :name, :code, uniqueness: true
    def self.types
      %w(Accounting::Asset Accounting::Liability Accounting::Equity Accounting::Revenue Accounting::Expense)
    end

    def balance(options={})
      if self.class == Account
        raise(NoMethodError, "undefined method 'balance'")
      else
        if self.normal_credit_balance ^ contra
          credits_balance(options) - debits_balance(options)
        else
          debits_balance(options) - credits_balance(options)
        end
      end
    end

    def credits_balance(options={})
      credit_amounts.balance(options)
    end

    def debits_balance(options={})
      debit_amounts.balance(options)
    end

    def self.balance(options={})
      if self.new.class == Account
        raise(NoMethodError, "undefined method 'balance'")
      else
        accounts_balance = BigDecimal.new('0')
        accounts = self.all
        accounts.each do |account|
          if account.contra
            accounts_balance -= account.balance(options)
          else
            accounts_balance += account.balance(options)
          end
        end
        accounts_balance
      end
    end

    def self.trial_balance
      if self.new.class == Accounting::Account
        Accounting::Asset.balance - (Accounting::Liability.balance + Accounting::Equity.balance + Accounting::Revenue.balance - Accounting::Expense.balance)
      else
        raise(NoMethodError, "undefined method 'trial_balance'")
      end
    end
  end
end

app/models/accounting/amount.rb
module Accounting
  class Amount < ApplicationRecord
    belongs_to :account, class_name: "Accounting::Account"
    belongs_to :entry, class_name: "Accounting::Entry"

    validates :type, :amount, :entry, :account, presence: true
    def account_name=(name)
        self.account = Accounting::Account.find_by_name(name)
      end

      protected

      # Support constructing amounts with account = "name" syntax
      def account_with_name_lookup=(v)
        if v.kind_of?(String)
          ActiveSupport::Deprecation.warn('Plutus was given an :account String (use account_name instead)', caller)
          self.account_name = v
        else
          self.account_without_name_lookup = v
        end
      end
      alias_method_chain :account=, :name_lookup
    end
end

app/models/accounting/amounts_extension.rb
module Accounting
  module AmountsExtension
    def balance(hash={})
      if hash[:from_date] && hash[:to_date]
        from_date = hash[:from_date].kind_of?(Time) ? hash[:from_date] : Time.parse(hash[:from_date].strftime('%Y-%m-%d 12:00:00'))
        to_date = hash[:to_date].kind_of?(Time) ? hash[:to_date] : Time.parse(hash[:to_date].strftime('%Y-%m-%d 12:59:59'))
        joins(:entry, :account).where('entries.date' => from_date..to_date).sum(:amount)
      else
        joins(:entry, :account).sum(:amount)
      end
    end

    def balance_for_new_record
      balance = BigDecimal.new('0')
      each do |amount_record|
        if amount_record.amount && !amount_record.marked_for_destruction?
          balance += amount_record.amount # unless amount_record.marked_for_destruction?
        end
      end
      return balance
    end
  end
end

app/models/accounting/asset.rb
module Accounting
  class Asset < Account
    self.normal_credit_balance = false
    def self.balance(options={})
      super(options)
    end
    def balance(options={})
      super(options)
    end
  end
end

app/models/accounting/credit_amount.rb
module Accounting
  class CreditAmount < Amount
  end
end

app/models/accounting/debit_amount.rb
module Accounting
  class DebitAmount < Amount
  end
end

app/models/accounting/equity.rb
module Accounting
  class Equity < Account
    self.normal_credit_balance = true
    def self.balance(options={})
      super(options)
    end
    def balance(options={})
      super(options)
    end
  end
end

app/models/accounting/expense.rb
module Accounting
  class Expense < Account
    self.normal_credit_balance = false
    def self.balance(options={})
      super(options)
    end
    def balance(options={})
      super(options)
    end
  end
end

app/models/accounting/liability.rb
module Accounting
  class Liability < Account
    self.normal_credit_balance = true
    def self.balance(options={})
      super(options)
    end
    def balance(options={})
      super(options)
    end
  end
end

app/models/accounting/revenue.rb
module Accounting
  class Revenue < Account
    self.normal_credit_balance = true
    def self.balance(options={})
      super(options)
    end
    def balance(options={})
      super(options)
    end
  end
end

app/controllers/accounting/accounting_controller.rb
class AccountingController < ApplicationController
  def index
  end
end 

app/controllers/accounting/accounts_controller.rb
module Accounting
  class AccountsController < ApplicationController
    before_action :set_account, only: [:show, :edit, :update, :destroy]
    before_action :set_type


    def index
        if params[:name].present?
          @accounts = type_class.search_by_name(params[:name])
        else
          @accounts = type_class.all.order(:code)
        end
        authorize @accounts
      end
    def show
    end

    def new
      @account = type_class.new
    end

    def edit
    end

    def create
      @accounts = Accounting::Account.all.order(:type)
      @account = Accounting::Account.create(account_params)
    end

    def update
      @accounts = Accounting::Account.all
      @account = Accounting::Account.find(params[:id])
      @account.update_attributes(account_params)
    end

    def activate
      @account = Accounting::Account.find(params[:id])
      @account.active!
      redirect_to accounting_index_url
    end
    def deactivate
      @account = Accounting::Account.find(params[:id])
      @account.inactive!
      redirect_to accounting_index_url
    end


    def destroy
      @account.destroy
      redirect_to accounts_url
    end

    private

    def set_type
      @type = type
    end

    def type
      Accounting::Account.types.include?(params[:type]) ? params[:type] : "Accounting::Account"
    end

    def type_class
      type.constantize
    end

    def set_account
      @account = type_class.find(params[:id])
    end

    def account_params
      params.require(type.underscore.gsub('/', '_').to_sym).permit(:name, :type, :code)
    end

  end
end

app/controllers/accounting/balance_sheet_controller.rb
class Accounting::BalanceSheetController < ApplicationController
  def index
    first_entry = Accounting::Entry.order('date ASC').first
    @from_date = first_entry ? first_entry.date: Date.today
    @to_date = params[:date] ? Date.parse(params[:date]) : Date.today
    @assets = Accounting::Asset.all
    @liabilities = Accounting::Liability.all
    @equity = Accounting::Equity.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/accounting/credit_payments_controller.rb
module Accounting
  class CreditPaymentsController < ApplicationController

    def new
      @line_item = LineItem.find(params[:line_item_id])
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @line_item = LineItem.find(params[:line_item_id])
      @entry = Accounting::Entry.create(entry_params)
      @entry.commercial_document = @line_item.order
      @entry.recorder = current_user
      if @entry.save
        @line_item.cash!
        redirect_to @line_item.stock.product, notice: "Payment saved successfully."
      else
        render :new
      end
      authorize @entry
    end

    def show
      @entry = Accounting::Entry.find(params[:id])
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end
end

app/controllers/accounting/dashboard_controller.rb
module Accounting
  class DashboardController < ApplicationController
    def index
      authorize [:accounting, :dashboard]
    end
  end
end

app/controllers/accounting/entries_controller.rb
module Accounting
  class EntriesController < ApplicationController
    def index
      if params[:query].present?
      @entries = Accounting::Entry.search_by_name(params[:query]).order(:date).page(params[:page]).per(30)

    else
      @entries = Accounting::Entry.includes(:commercial_document, :recorder).all.order('date DESC').page(params[:page]).per(30)
      @from_date = params[:from_date] ? Time.parse(params[:from_date]) : Time.now.beginning_of_day
      @to_date = params[:to_date] ? Time.parse(params[:to_date]) : Time.now.end_of_day
      respond_to do |format|
        format.html
        format.pdf do
          pdf = EntriesPdf.new(@entries, @from_date, @to_date, view_context)
            send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Entries Report.pdf"
        end
      end
    end
    authorize @entries
  end

    def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entries = Accounting::Entry.all
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      authorize @entry
    end

    def show
      @entry = Accounting::Entry.find(params[:id])
    end
    def scope_to_date
      @entries = Accounting::Entry.created_between(params[:from_date], params[:to_date])
      @from_date = params[:from_date] ? Time.parse(params[:from_date]) : Time.now.beginning_of_day
      @to_date = params[:to_date] ? Time.parse(params[:to_date]) : Time.now.end_of_day
      respond_to do |format|
        format.html
        format.pdf do
          pdf = EntriesPdf.new(@entries, @from_date, @to_date, view_context)
            send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Entries Report.pdf"
        end
      end
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end
end

app/controllers/accounting/income_statement_controller.rb
class Accounting::IncomeStatementController < ApplicationController
  def index
    @from_date = params[:from_date] ? Date.parse(params[:from_date]) : Date.today.at_beginning_of_month
    @to_date = params[:to_date] ? Date.parse(params[:to_date]) : Date.today
    @revenues = Accounting::Revenue.all
    @expenses = Accounting::Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.pdf do
        pdf = Accounting::IncomeStatementPdf.new(@revenues, @expenses,  @from_date, @to_date, view_context)
        send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Income Statement.pdf"
      end
    end
  end
end

app/controllers/accounting/reports_controller.rb
module Accounting
  class ReportsController < ApplicationController
    def index
    end
  end
end

app/controllers/accounting_controller.rb
class AccountingController < ApplicationController
  def index
    if params[:name].present?
      @active_accounts = Accounting::Account.includes(:main_account).active.all.order(:code).page(params[:page]).per(30).search_by_name(params[:name])
      @inactive_accounts = Accounting::Account.includes(:main_account).inactive.all.order(:code).page(params[:page]).per(30).search_by_name(params[:name])
    else
      @active_accounts = Accounting::Account.includes(:main_account).active.all.order(:code).page(params[:page]).per(30)
      @inactive_accounts = Accounting::Account.includes(:main_account).inactive.all.order(:code).page(params[:page]).per(30)

      first_entry = Accounting::Entry.order('date ASC').first
      @from_date = first_entry ? first_entry.date: Date.today
      @to_date = params[:date] ? DateTime.parse(params[:date]) : Date.today
      @assets = Accounting::Asset.active.all.order(:code)
      @liabilities = Accounting::Liability.active.all.order(:code)
      @equity = Accounting::Equity.active.all.order(:code)
      @revenues = Accounting::Revenue.all.order(:code)
      @expenses = Accounting::Expense.all.order(:code)
      @entries = Accounting::Entry.all.order(:date)
    end
  end
end

app/views/accounting/entries/_edit.html.erb
<div class="modal-header">
  <h4><%= "Editing #{@entry.name}" %></h4>
</div>
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for @entry, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors text-danger">
        </ul>

        <div class="form-group">
          <%=f.input :date %>
        </div>
        <div class="form-group">
          <%=f.input :description %>
        </div>
        <div class="form-group">
          <%=f.input :reference_number %>
        </div>
      </div>
      <%=simple_fields_for :debit_amounts do |ff| %>
      <%=ff.input :amount %>
      <%=ff.input :account, collection: Accounting::Account.all.pluck(:name) %>
      <% end %>
      <%=simple_fields_for :credit_amounts do |ff| %>
      <%=ff.input :amount %>
      <%=ff.input :account, collection: Accounting::Account.all.pluck(:name) %>
      <% end %>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/accounting/entries/_index.html.erb
<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.date.strftime("%B %e, %Y") %></td>

    <td><%=link_to entry.description.truncate(200), accounting_entry_path(entry) %></td>
    <td><%=entry.commercial_document.try(:full_name) %></td>
    <td><%=entry.recorder.try(:full_name) %></td>
    <td><span class='pull-right'><%=number_to_currency entry.debit_amounts.sum(:amount) %></span></td>
  </tr>
<% end %>

app/views/accounting/entries/_new.html.erb
<div class="modal-header">
<h3 class="title">New Entry</h3>
</div>
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for @entry, remote: true, html: { style: "display:inline;" } do |f| %>
    <div class="modal-body">
      <ul class="errors text-danger">
      </ul>
<div class="row">
  <div class="col-md-6">
        <%=f.input :date, as: :string, input_html: { class: "datepicker" } %>
</div>
<div class="col-md-6">
<%=f.input :reference_number %>

</div>
</div>
          <%=f.input :description %>

    <%=f.simple_fields_for :debit_amounts do |ff| %>
    <%=ff.input :amount %>
    <div class="row">
      <div class="col-md-12">
    <%=ff.input :account, collection: Accounting::Account.all.pluck(:name), input_html: {class: 'input-medium'} %>
  </div>
</div>
    <% end %>
    <%=f.simple_fields_for :credit_amounts do |ff| %>
    <%=ff.input :amount %>
    <%=ff.input :account, collection: Accounting::Account.all.pluck(:name) %>
    <% end %>
    <div class="modal-footer">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", "#", class: "btn pull-left", data: {dismiss: "modal"} %>
    </div>
  <% end %>
  </div>
</div>

app/views/accounting/entries/_save.js.erb
$("ul.errors").html("")
<% if @entry.errors.any? %>
  <% @entry.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#entryModal").modal("hide")
    window.location.reload();
<% end %>

app/views/accounting/entries/create.js.erb
<%= render "save" %>

app/views/accounting/entries/index.html.erb
<div id="entryModal" class="modal fade"></div>
<div class="row">
  <div class="col-md-12">
  	<div class="box box-solid">
    	<div class="box-body">
				<div class="col-md-4">
			  	<ul class="nav navbar-nav">
			      <li class="dropdown">
			        <button href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">Show Activity <b class="caret"></b></button>
			        <ul class="dropdown-menu dropdown-menu-right">
			          <li><%=link_to 'This Day', scope_to_date_accounting_entries_path(:from_date => Time.zone.now.beginning_of_day, :to_date => Time.zone.now.end_of_day, format: 'pdf') %></li>
						    <li> <%=link_to 'This Week', scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') %></li>
						    <li> <%=link_to 'This Month', scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') %></li>
			        </ul>
			      </li>
			    </ul>
				</div>
				<div class="col-md-4">
			    <%=form_tag accounting_entries_path, method: :get do %>
			      <div class="input-group stylish-input-group">
			        <%=text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search Inventory...'%>
			        <span class="input-group-btn">
			          <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
			            <i class="fa fa-search"></i>
			          <% end %>
			        </span>
			      </div>
			    <% end %>
				</div>
				<div class="col-md-4">
					<span class="pull-right"><%=link_to "New Entry", new_accounting_entry_path, remote: true, class: "btn btn-primary" %> </span>
				</div>
			</div>
			<hr>
			<div class="row">
			  <div class="col-md-3">
			    <span class="pull-right title">Filter Date:</span>
			  </div>
			  <div class="col-md-9">
			    <%= form_tag({:action => 'index'}, {:method => :get})  do %>
			      <div class="row">
			        <div class="col-md-4">
			          <%= text_field_tag :from_date, @from_date, :class => 'datepicker form-control'%>
			        </div>
			        <div class="col-md-4">
			          <%= text_field_tag :to_date, @to_date, :class => 'form-control datepicker'%>
			        </div>
			        <div class="col-md-4">
			        	<button type="submit" class="btn btn-success active"> Go </button>
			          <%=link_to "PDF", accounting_entries_path(format: 'pdf', from_date: @from_date, to_date: @to_date), class: "btn btn-default active"%>
			        </div>
			      </div>
			    <% end %>
			  </div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-12">
				  <div class="card">
				    <div class="header">
				    </div>
						<div class="content">
							<div class="table table-responsive">
								<table class="table table-striped">
									<thead>
										<tr class="title">
			                <th> Date </th>
											<th> Description </th>
			                <th> Customer </th>
											<th> Employee </th>
											<th> Amount</th>
										</tr>
									</thead>
									<tbody class="entry-index">
										<%=render 'index' %>
									</tbody>
								</table>
								<div class="modal-footer">
				          <center><%= paginate @entries, :window => 1 %></center>
				        </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/accounting/entries/new.js.erb
$("#entryModal").html("<%= escape_javascript(render 'new') %>")
$('#entryModal').modal({backdrop: 'static', keyboard: false, show: true})
$('.datepicker').datepicker({
format: "yyyy/mm/dd/",
orientation: "auto bottom",
todayHighlight: 'true',
autoclose: 'true'
});
$("#accounting_entry_debit_amounts_attributes_0_account").select2({
   theme: "bootstrap",
   placeholder: 'Select Account',
   dropdownAutoWidth : true
  });
  $("#accounting_entry_credit_amounts_attributes_0_account").select2({
     theme: "bootstrap",
     placeholder: 'Select Account',
     dropdownAutoWidth : true
    });

app/views/accounting/entries/show.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="box box-solid">
			<div class="box-header">
				<h4>Entry Details</h4>
					<div class="pull-right">
				  	<ul class="nav navbar-nav">
				      <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> <b class="caret"></b></a>
				        <ul class="dropdown-menu dropdown-menu-right">
				          <li><%=link_to 'Delete', accounting_entry_path(@entry), method: :delete, data: {confirm: 'Are you sure?'} %></li>
				        </ul>
				      </li>
				    </ul>
				  </div>
				</h4>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<p><strong>Recipient</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.commercial_document.try(:name) %></span><br>
							<hr>
						<p><strong>Description</strong></p>
						<hr>
					<span>&nbsp &nbsp &nbsp<%=@entry.description %></span><br>



						<p><strong>Date</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.date.strftime("%B %e, %Y") %></span>

						<hr>

						<p><strong>Reference Number</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.reference_number%></span>

						<hr>

						<p><strong>Debited Account(s)</strong></p>
						<%@entry.debit_amounts.each do |d|%>
							<div class="row">
								<div class="col-md-12">
									&nbsp &nbsp &nbsp<%=d.account.name %><span class="pull-right"><%=number_to_currency d.amount %></span>
								</div>
							</div>
						<%end %>

						<hr>

						<p><strong>Credited Account(s)</strong></p>
						<%@entry.credit_amounts.each do |d|%>
							<div class="row">
								<div class="col-md-12">
									&nbsp &nbsp &nbsp<%=d.account.name %> <span class="pull-right"><%=number_to_currency d.amount %></span>
								</div>
							</div>
						<% end %>
						<br>
						<div class="modal-footer">
							<%= link_to "Cancel", accounting_entries_path, class: 'btn btn-xs pull-left' %>
							<%=link_to "Edit Entry", edit_accounting_entry_path(@entry), class: "btn btn-primary" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/accounting/entries/update.js.erb
<%= render "save" %>