config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "store/index"
  root :to => "store#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    resources :stocks, only: [:new, :create], module: :products
  end
  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
  end
  resources :carts
  resources :orders do
      match "/guest" => "orders#guest",  via: [:post], on: :member
      match "/print" => "orders#print",  via: [:get], on: :member
      match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
      match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
      match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection



    end
  resources :members do
    resources :payments, only: [:new, :create], module: :members
    resources :line_items, only: [:index], module: :members do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :members
    end
  end
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do 
    resources :payments, only: [:new, :create], module: :suppliers
  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :categories
  resources :wholesales
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks

  end
  namespace :wholesales do
    resources :line_items
    resources :orders
  end
  resources :businesses
  resources :info, only: [:index]
  resources :users, only: [:show, :edit, :update]
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index]
  namespace :accounting do
    resources :balance_sheet, only:[:index]
    resources :income_statement, only:[:index]
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member

    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :entries do
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :warranties, only: [:new, :create]
  resources :birs
  resources :retail_pricelists, only: [:index]
  resources :wholesale_pricelists, only: [:index]

end

app/controllers/low_stock_products_controller.rb
class LowStockProductsController < ApplicationController
  def index
    @products = Product.low_stock
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ProductsPdf.new(@products, view_context)
              send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Low Stock Products Report.pdf"
      end
    end
  end
end

app/views/low_stock_products/index.html.erb
<div id="product-modal" class="modal fade"></div>
<div class="row">
                    <div class="col-md-12">
                        <div class="box box-default">
                            <div class="panel-heading">
                                 <div class="row">
                                   <div class="col-md-3">
                                     <ul class="nav navbar-nav">
                                             <li class="dropdown">
                                               <li class="dropdown">
                                               <button href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">All Products <b class="caret"></b></button>
                                               <ul class="dropdown-menu dropdown-menu-right">
                                                   <li><%=link_to 'Available Products', available_products_path %></li>
                                                <li><%=link_to 'All Products', products_path %></li>
                                                 <li><%=link_to 'Low Stock', low_stock_products_path %></li>
                                                  <li><%=link_to 'Out of Stock', out_of_stock_products_path %></li>

                                               </ul>
                                             </li>
                                           </ul>
                                </div>

                                <div class="col-md-6">
                                  <%=form_tag products_path, method: :get do %>
                                    <div class="input-group stylish-input-group">
                                      <%=text_field_tag :name, params[:name], class: 'form-control', placeholder: 'Search Inventory...'%>
                                      <span class="input-group-btn">
                                        <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
                                          <i class="fa fa-search"></i>
                                        <% end %>
                                      </span>
                                    </div>
                                  <% end %>
                                </div>
                                <div class="col-md-3">
                                  <%=link_to new_product_path, remote: true do %>
                                  <span class="btn btn-primary btn-icon pull-right"><i class="fa fa-plus"></i> New Product</span>
                                  <% end %>
                                </div>
                              </div>
</span>                                </h4>
                                <p class="category"></p>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover">
                                    <thead>
                                        <th>Name</th>
                                        <th><span class='pull-right'> Price</span></th>
                                        <th><span class='pull-right'> Wholesale Price </span> </th>

                                        <th><span class='pull-right'>In Stock</span></th>
                                        <th>Stock Alert</th>

                                    </thead>
                                    <tbody>
                                    <% @products.each do |product| %>
                                        <tr class="<%="text-danger" if product.out_of_stock?%>">
                                            <td><%=link_to product.name, product %></td>
                                            <td><span class='pull-right'><%=number_to_currency product.price%></span></td>
                                            <td><span class='pull-right'><%=number_to_currency product.wholesale_price%></span></td>
                                            <td><span class='pull-right'><%=product.quantity %></span></td>
                                            <td><span><%=product.stock_status.try(:titleize) %></span></td>
                                            <td><%=link_to "New Stock", new_product_stock_path(product), class: "btn btn-primary btn-sm active" %>

                                            </td>

                                        </tr>

                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>






    </div>