config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "store/index"
  root :to => "store#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    resources :stocks, only: [:new, :create], module: :products
  end
  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
  end
  resources :carts
  resources :orders do
      match "/guest" => "orders#guest",  via: [:post], on: :member
      match "/print" => "orders#print",  via: [:get], on: :member
      match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
      match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
      match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection



    end
  resources :members do
    resources :payments, only: [:new, :create], module: :members
    resources :line_items, only: [:index], module: :members do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :members
    end
  end
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do 
    resources :payments, only: [:new, :create], module: :suppliers
  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :categories
  resources :wholesales
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks

  end
  namespace :wholesales do
    resources :line_items
    resources :orders
  end
  resources :businesses
  resources :info, only: [:index]
  resources :users, only: [:show, :edit, :update]
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index]
  namespace :accounting do
    resources :balance_sheet, only:[:index]
    resources :income_statement, only:[:index]
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member

    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :entries do
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :warranties, only: [:new, :create]
  resources :birs
  resources :retail_pricelists, only: [:index]
  resources :wholesale_pricelists, only: [:index]

end

app/controllers/wholesales/line_items_controller.rb
module Wholesales
  class LineItemsController < ApplicationController
    def create
      @cart = current_cart
      @line_item = @cart.line_items.create(line_item_params)
      respond_to do |format|
        if @line_item.save
          @line_item.wholesale!
          @cart.add_line_item(@line_item)
          format.html { redirect_to wholesales_url }
          format.js   { @current_item = @line_item }
        else
          format.html { redirect_to wholesales_url }
        end
      end
    end

    def destroy
      @cart = LineItem.find(params[:id])
      @cart.destroy
      redirect_to wholesales_url
    end

    private
    def line_item_params
      params.require(:line_item).permit(:user_id, :stock_id, :quantity, :unit_cost, :total_cost)
    end
  end
end

app/controllers/wholesales/orders_controller.rb
module Wholesales
  class OrdersController < ApplicationController
    def index
      @orders = Order.all.order(:created_at)
    end
    def new
      @cart = current_cart
        if @cart.line_items.empty?
          redirect_to store_url, notice: "Your cart is empty"
        return
      end
      @order = Order.new
    end
    def create
      @order = Order.new(order_params)
      @order.add_line_items_from_cart(current_cart)
      @order.employee = current_user
      respond_to do |format|
        if @order.save
          @order.wholesale!
          @order.create_entry
          Cart.destroy(session[:cart_id])
          session[:cart_id] = nil
          format.html do
            if @order.credit?
              redirect_to print_order_url(@order), notice: 'Credit transaction saved successfully.'
            else
              redirect_to print_order_url(@order), notice: 'Thank you for your order.'
            end
          end
          format.json { render json: @order, status: :created,
          location: @order }
        else
          @cart = current_cart
          format.html { render action: "new" }
          format.json { render json: @order.errors,
          status: :unprocessable_entity }
        end
      end
      InvoiceNumber.new.generate_for(@order)
    end

    def show
      @order = Order.find(params[:id])
    end

    private
    def order_params
      params.require(:order).permit(:user_id, :pay_type, :delivery_type, :date)
    end
  end
end

app/controllers/wholesales_controller.rb
class WholesalesController < ApplicationController
  def index
    if params[:name].present?
      @stocks = Stock.search_by_name(params[:name])
    else
      @stocks = Stock.all
    end
    authorize :store
  @cart = current_cart
  @line_item = LineItem.new
  @order = Order.new
  @order.build_discount
end
end

app/views/wholesales/index.html.erb
<section class="content-header">
  <ol class="breadcrumb">
    <li class="active">ITWORX POS Software - by ITWORX Technology Services</li>
  </ol>
  <h1><%=Business.last.try(:name) %> (WHOLESALE)</h1>
  <small class="text-muted"><%=Business.last.try(:address) %></small>
</section>
<br>
<div class="row">
  <div class="col-md-7">
    <div class="box box-default">
      <div class="panel-heading">
      </div>
      <div class="box-body">
        <div class="col-md-12">
          <% if params[:name].present? %>
            <%=form_tag wholesales_path, url: :wholesales, method: :get do %>
              <div class="input-group stylish-input-group">
                <%=text_field_tag :name, params[:name], class: 'form-control input-lg', placeholder: 'Search Inventory...' %>
                <span class="input-group-btn">
                  <%= button_tag(type: 'submit', class: "btn btn-flat btn-lg") do %>
                    <i class="fa fa-search"></i>
                  <% end %>
                </span>
              </div>
            <% end %>
          <% else %>
            <%=form_tag wholesales_path, url: :wholesales, method: :get do %>
              <div class="input-group stylish-input-group">
                <%=text_field_tag :name, params[:name], autofocus: true, class: 'form-control input-lg', placeholder: 'Search Inventory...' %>
                <span class="input-group-btn">
                  <%= button_tag(type: 'submit', class: "btn btn-flat btn-lg") do %>
                    <i class="fa fa-search"></i>
                  <% end %>
                </span>
              </div>
            <% end %>
          <% end %>
        </div>
        <hr>
        <br>
        <% if params[:name].present? && @stocks.count > 0 %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>In Stock </th>
                <th>Product</th>
                <th>Price </th>
                <th>Quantity </th>
                <th></th>
              </tr>
            </thead>
            <% @stocks.each do |stock| %>
              <tbody>
                <tr>
                  <td><%=number_to_currency(stock.in_stock.round, unit: "")%></td>
                  <td><%=stock.name.truncate(20) %></td>
                  <td><%=number_to_currency stock.wholesale_price %></td>
                  <%=simple_form_for @line_item, url: :wholesales_line_items do |f| %>
                    <td class="col-md-3">
                      <% if stock.out_of_stock? %>
                        <%=f.input :quantity, readonly: true, label: false %>
                      <% else %>
                        <%=f.input :quantity,  input_html: {value: 1}, autofocus: true, label: false %>
                      <% end %>
                      <%=f.input :stock_id, input_html: {value: stock.id }, as: :hidden %>
                      <%=f.input :unit_cost, input_html: { value: stock.wholesale_price}, as: :hidden %>
                    </td>
                    <td>
                      <% if  stock.out_of_stock? %>
                        <span class="text-danger btn"> Out of Stock </span>
                      <% else %>
                        <%=f.submit "Add", data: {disable_with: "Adding Product..."}, class: "btn btn-primary btn-sm active" %>
                      <% end %>
                    </td>
                  <% end %>
                </tr>
              </tbody>
            <% end %>
          </table>
        <% elsif @stocks.count.zero? %>
          <p class="alert alert-info"> Product not found.<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> </p>
        <% end %>

      </div>
    </div>
  </div>
  <div class="col-md-5" id="cart">
    <div class="box box-solid">
      <div class="box-body">
        <% if @cart.line_items.blank? %>
          <center><%=image_tag('empty_cart.png', height: 150, width: 150) %></center>
        <% else %>
          <div class="col-md-12">
            <h4> <i class="fa fa-cart-plus fa-2x"></i> <span class='badge bg-green'><%=@cart.line_items.count %></span>
              <span class="pull-right">
                <%= link_to 'Empty Cart', @cart, method: :delete, confirm: 'Are you sure?', class: "btn btn-danger btn-xs" %>
              </span>
            </h4>
            <br>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-12">
              <%=render @cart.line_items.sort_by{|l| l.stock_name } %>
            </div>
            <div class="col-md-12">
              <div class="pull-left">
                <h3 class="title"> <b>Sub Total</b> </h3>
              </div>
              <div class="pull-right">
                <h3 class="title"> <b><%=number_to_currency @cart.total_price %></b></h3>
              </div>
            </div>
          </div>
          <hr>
          <%=simple_form_for @order, url: :wholesales_orders do |f| %>
            <span><label>Customer</label> <span class="pull-right"><%= link_to 'New Customer', new_member_path, remote: true %></span></span>
            <%=f.input :user_id, label: false, collection: Member.all.map{|a| [a.full_name, a.id] } || 'Guest', input_html: {id: 'order_user_id'} %>
            <input type="hidden" name="total" id="total" value="<%= @cart.total_price %>" oninput="calculateChange()">
            <%=f.input :pay_type, collection: Order.pay_types.keys.to_a.map{|a| [a.titleize, a]}, default: Order.pay_types.first%>
            <%=f.input :date, as: :string, input_html: {class: 'datepicker'}, default: Time.zone.now %>
            <div id='cash_payment_details'>
              <%=f.input :discounted, as: :boolean, input_html: { id: 'order_discount'} %>
              <div id="discount_details" style="display:none;">
                <%=f.simple_fields_for :discount do |ff| %>
                  <div class="form-group has-warning">
                   <%= ff.input :amount, input_html: {oninput: 'calculateChange()', class: 'input-lg text-danger', value: 0}, label: "Discount Amount" %>
                 </div>
               <% end %>
              </div>
              <%=f.input :cash_tendered, input_html: {oninput: 'calculateChange()', class: 'input-lg'}, label: "Cash / Check Amount" %>
              <%=f.input :change, input_html: { class: 'input-lg'}, readonly: true %>
            </div>
            <%=f.input :delivery_type, collection: Order.delivery_types.keys.to_a.map{|a| [a.titleize, a]}, default: Order.delivery_types.keys.to_a.third%>

            <%=f.submit "Checkout", class: 'btn btn-success btn-block btn-lg' %>
            <br>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $("#order_user_id").select2({
      theme: "bootstrap"
    });
  });
</script>
<script>
  $(document).ready(function() {
    $("#order_pay_type").select2({
      theme: "bootstrap"
    });
    $("#order_delivery_type").select2({
      theme: "bootstrap"
    });
  });
</script>
<script>
  var checkbox = document.getElementById('order_discount');
  var details_div = document.getElementById('discount_details');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div.style['display'] = 'block';
     } else {
       details_div.style['display'] = 'none';
     }
  };
</script>
<div id="member-modal" class="modal fade"></div>