config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "store/index"
  root :to => "store#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    resources :stocks, only: [:new, :create], module: :products
  end
  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
  end
  resources :carts
  resources :orders do
      match "/guest" => "orders#guest",  via: [:post], on: :member
      match "/print" => "orders#print",  via: [:get], on: :member
      match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
      match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
      match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection



    end
  resources :members do
    resources :payments, only: [:new, :create], module: :members
    resources :line_items, only: [:index], module: :members do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :members
    end
  end
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do 
    resources :payments, only: [:new, :create], module: :suppliers
  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :categories
  resources :wholesales
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks

  end
  namespace :wholesales do
    resources :line_items
    resources :orders
  end
  resources :businesses
  resources :info, only: [:index]
  resources :users, only: [:show, :edit, :update]
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index]
  namespace :accounting do
    resources :balance_sheet, only:[:index]
    resources :income_statement, only:[:index]
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member

    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :entries do
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :warranties, only: [:new, :create]
  resources :birs
  resources :retail_pricelists, only: [:index]
  resources :wholesale_pricelists, only: [:index]

end

app/controllers/accounting/reports_controller.rb
module Accounting
  class ReportsController < ApplicationController
    def index
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end
end 

app/views/reports/index.html.erb
<h3>Reports Section</h3>

<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
      <div class="box-header with-border">
        <h4>SALES</h4>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-md-4">
            <%=link_to scope_to_date_orders_path(from_date: Time.zone.now.beginning_of_day, to_date: Time.zone.now.end_of_day, format: 'pdf') do %>
              <h4> Daily Sales Report </h4>
              <p> Generate daily sales report for today. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_orders_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') do %>
              <h4> Weekly Sales Report </h4>
              <p> Generate daily sales report for today. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_orders_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') do %>
              <h4> Monthly Sales Report </h4>
              <p> Generate daily sales report for today. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-6 col-md-offset-3">
            <h4> Custom Sales Report </h4>
            <%= form_tag({:action => "scope_to_date", controller: "orders", format: 'pdf'}, {:method => :get})  do %>
              <div class="row">
                <div class="col-md-5">
                  <div class="form-group">
                    <%= text_field_tag :from_date, @from_date, :class => 'datepicker form-control border-input', :placeholder => "From " %>
                  </div>
                </div>
                <div class="col-md-5">
                  <div class="form-group">
                    <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker', :placeholder => "To " %>
                  </div>
                </div>
                <div class="col-md-2">
                  <button type="submit" class="btn btn-success active"> Go </button>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="box box-danger">
      <div class="box-header with-border">
        <h4>INVENTORIES</h4>
      </div>
      <div class="box-body ">
        <div class="row">
          <div class="col-md-4">
            <%=link_to low_stock_products_path(format: 'pdf'), class: 'text-warning' do %>
              <h4><span class='text-danger'><i class='fa fa-file-text-o'></i> Low Stock Products </span> </h4>
              <p>Generate report for all low stock products. </p>
            <% end %>
            <hr >
          </div>
          <div class="col-md-4">
            <%=link_to out_of_stock_products_path(format: 'pdf'), class: 'text-danger' do %>
              <h4 class="text-danger"><i class='fa fa-file-text-o text-danger'></i>Out of Stock Products </h4>
              <p>Generate report for expired products. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4">
            <%=link_to expired_products_path(format: 'pdf'), class: 'text-danger' do %>
              <h4 class="text-danger"><i class='fa fa-file-text-o text-danger'></i> Expired Products </h4>
              <p>Generate report for all out of stock products. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4 col-md-offset-4">
            <%=link_to products_path(format: 'pdf') do %>
              <h4 class="text-info"> Current Inventory Status </h4>
              <p class="category"> Generate current status of inventories. </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="box box-warning">
      <div class="box-header with-border">
        <h4>PURCHASES</h4>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-md-4 ">
            <%=link_to scope_to_date_stocks_path(from_date: Time.zone.now.beginning_of_day, to_date: Time.zone.now.end_of_day, format: 'pdf') do %>
              <h4> Daily Purchase </h4>
              <p> Generate report for purchases entered this day. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4 ">
            <%=link_to scope_to_date_stocks_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') do %>
              <h4> Weekly Purchase </h4>
              <p> Generate report for purchases entered this day. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4 ">
            <%=link_to scope_to_date_stocks_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') do %>
              <h4> Monthly Purchase </h4>
              <p> Generate report for purchases entered this day. </p>
            <hr>
            <% end %>
          </div>
          <div class="col-md-6 col-md-offset-3 ">
            <h4> Custom Purchases Report </h4>
            <%= form_tag({:action => "scope_to_date", controller: "stocks", format: 'pdf'}, {:method => :get})  do %>
              <div class="row">
                <div class="col-md-5">
                  <div class="form-group">
                    <%= text_field_tag :from_date, @from_date, :class => 'datepicker form-control border-input', :placeholder => "From " %>
                  </div>
                </div>
                <div class="col-md-5">
                  <div class="form-group">
                    <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker', :placeholder => "To " %>
                  </div>
                </div>
                <div class="col-md-2">
                  <button type="submit" class="btn btn-success active"> Go </button>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="box box-success">
      <div class="box-header with-border">
        <h4>RECEIVABLES</h4>
      </div>
      <div class="box-body ">
        <%=link_to credits_path(format: 'pdf') do %>
          <h4>Due from Customers </h4>
          <p>Generate report for credits due from customers </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="box box-success">
      <div class="box-header with-border">
        <h4>PAYABLES</h4>
      </div>
      <div class="box-body ">
        <%=link_to payables_path(format: 'pdf') do %>
          <h4>Payable to Suppliers </h4>
          <p>Generate report for accounts payable to creditors </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="box box-success">
      <div class="box-header with-border">
        <h4>ACCOUNT</h4>
      </div>
      <div class="box-body ">
        <%=link_to accounting_income_statement_index_path(format: 'pdf') do %>
          <h4> Income Statement </h4>
          <p>Generate Income Statement of your business </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="box box-info">
      <div class="box-header with-border">
        <h4>TRANSACTIONS</h4>
      </div>
      <div class="box-body ">
        <div class="row">
          <div class="col-md-3">
            <%=link_to scope_to_date_accounting_entries_path(:from_date => Time.zone.now.beginning_of_day, :to_date => Time.zone.now.end_of_day, format: 'pdf') do %>
              <h4>Daily</h4>
              <p>Generate transactions of your business for this day.</p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-3">
            <%=link_to scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') do %>
              <h4>Weekly</h4>
              <p>Generate transactions of your business for this week.</p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-3">
            <%=link_to scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') do %>
              <h4>Monthly</h4>
              <p>Generate transactions of your business for this month.</p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-3">
            <%= link_to scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_year, to_date: Time.zone.now.end_of_year, format: 'pdf') do %>
              <h4>Yearly</h4>
              <p>Generate transactions of your business for this year.</p>
            <% end %>
            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>